theme: minima
title: Hacker's Server
author:u5u7hu
email: philani.thobisa.ndlovu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hack the planet! Young hacker from South Africa sharing hacking tools and scripts.

# social links
twitter_username: BareChestedMan
github_username:  u5u7hu

show_excerpts: true # set to false to remove excerpts on the homepage
